--- #YAML:1.0
name:               IO-Vectored
version:            0.100
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:      0
    Exporter:  0
    XSLoader:  0
resources:
    bugtracker:  https://github.com/hoytech/IO-Vectored/issues
    repository:  git://github.com/hoytech/IO-Vectored.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
